### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: results.then is not a function

### ISSUE THREAD

**Issue by pandiarajanvp** [coreyshaw/mysql-simple-query#2]
while getting data from mysql with async /await its shows results.then is not a function,
1.How to Configure with Database

**Comment by coreyshaw** [comment]
Hello,

Have you tried constructing your return like this?

const results = await pool.query(db.query());

This library is intended to generate the raw mysql query and then pass the query to mysql to handle it. Please see the example below.

const db = new SimpleQuery();

db.select('*');
db.from('some_database');
db.where('id', 1);

const query = db.query();
const results = await pool.query(query);

Hope that helps
